---
title: Recortar un sonido
hero_image: images/banner.png
description: Recortar un sonido
version: 4
listed: false
copyedit: false
last_tested: "2021-06-08"
steps:
  - 
    title: Recortar un sonido
